### ISSUE TITLE
Right click go to channel

### ISSUE THREAD

**Issue by DavidHenryThoreau** [lekma/plugin.video.invidious#1]
Hi,

I'm using the kodi invidous application thanks for shared :)
Can you add a right click option in videos in order to go to channel directly ?

**Comment by lekma** [comment]
I added a tentative solution in 39819050bc61a22c00b8afb90855e3636d35eb60, the navigation is borked though after you go to the channel and I don't know yet how to fix it.Please test and tell me if I am on the right track.

**Comment by DavidHenryThoreau** [comment]
Perfect, it's working :)

**Comment by lekma** [comment]
should be fixed inccf1b8232d4a0922a4beb7a5cb02984f5637074c
