### ISSUE TITLE
Add a repository for plugin.video.invidious

### ISSUE THREAD

**Issue by DavidHenryThoreau** [lekma/plugin.video.invidious#10]
Add a [repository ](https://kodi.wiki/view/HOW-TO:Create_a_repository_for_add-ons) for plugin.video.invidious in order to be up to date.

**Comment by DavidHenryThoreau** [comment]
[The repository is created](https://github.com/lekma/plugin.video.invidious/pull/11)

**Comment by lekma** [comment]
a couple of comments:
- I have a couple of addons in dev right now and one more coming up, so, I will probably create a repository (if only for my own sanity).
- kodi 19 (python3 only) is coming up so I'll have to review all the addons and fix them accordingly.

so, the repository will happen but not right now. please be patient.

(I'll keep this issue open as a reminder)

**Comment by lekma** [comment]
this should be working now.

do you mind installing the [repo](https://github.com/lekma/repository.lekma/) and checking that installing from Kodi works correctly?

thanks for your help

**Comment by DavidHenryThoreau** [comment]
For me the repo is working once repository installed i'm getting the 0.2.0 and can play videos.

**Comment by lekma** [comment]
tahnks for testing
