### ISSUE TITLE
does not get videos anymore

### ISSUE THREAD

**Issue by slynobody** [lekma/plugin.video.invidious#107]
instance-chooser does not work anymore. no videos in kodi though f.e. https://yewtu.be/ works in browser.

**Comment by lekma** [comment]
no public instance, right now, advertise public api support (https://api.invidious.io/).
I'll fix the the instance chooser by the end of the week, but, unfortunately, that won't fix your problem (I feel that invidious public instances are more and more reluctant to providing/maintaining a public json service...)

**Comment by slynobody** [comment]
Thank you for the information (and your work!!!). then the public api advertisement died 2 weeks ago across all currently active instances? do you know any (working) alternative to invidious for watching youtube (with kodi-option)?

**Comment by lekma** [comment]
have a look around my repo...

**Comment by lekma** [comment]
...or you could run your own instance of invidious
...or https://github.com/anxdpanic/plugin.video.youtube

**Comment by slynobody** [comment]
mytube seems to work great, thank you!
