### ISSUE TITLE
 script.module.nutting missing

### ISSUE THREAD

**Issue by nidamanx** [lekma/plugin.video.invidious#108]
Hi,
installing on a Raspberry with LibreELEC 12.0.1 and Kodi Media Center 21.1 (21.1.0) Git:21.1-Omega
I got this error:
"The dependency on script.module.nutting 1.2.5 could not be satisfied"

I was here to download and manually install script.module.nutting, but is also not available.
https://mirrors.kodi.tv/addons/omega/

Any Ideas?
Thanks

**Comment by lekma** [comment]
install this repo: https://github.com/lekma/repository.lekma
or get it directly from: https://github.com/lekma/repository.lekma/raw/refs/heads/master/nexus/script.module.nuttig/script.module.nuttig-1.3.0.zip

**Comment by nidamanx** [comment]
Perfect. Thanks!
