### ISSUE TITLE
Date and hour in description

### ISSUE THREAD

**Issue by DavidHenryThoreau** [lekma/plugin.video.invidious#18]
1/ In the description the date is not the same on YouTube website than in Invidous.
For example : 
* this video on YouTube website the url (https://www.youtube.com/watch?v=OL_2nWvv4VE -> 18 avr. 2020)
* the same video on Invidious Kodi extension (2020-04-21 10:44:51) 

2/ The hour can vary depends on the searched hour for the test it was 10:44

**Comment by lekma** [comment]
I think it's a bug in invidious, compare the 'published' field in the following urls:
- https://invidio.us/api/v1/videos/OL_2nWvv4VE
- https://invidio.us/api/v1/channels/UCiEk4xHBbz0hZNIBBpowdYQ/videos?page=1
it's the seventh item (index 6) in the list from the second link.

I think the best course of action would be to report this inconsistency as a bug on invidious issue tracker.

**Comment by lekma** [comment]
also if you play the video and hit the 'i' key (for information) you get the correct date (because we hit the first link at this point)

**Comment by DavidHenryThoreau** [comment]
Issue reported https://github.com/omarroth/invidious/issues/1184

**Comment by DavidHenryThoreau** [comment]
matthewmcgarvey add an answer : 
https://github.com/iv-org/invidious/issues/1184#issuecomment-706430601

**Comment by lekma** [comment]
can't do anything about that
