### ISSUE TITLE
Another Kodi Addon

### ISSUE THREAD

**Issue by Perflyst** [lekma/plugin.video.invidious#22]
There is also another addon with the same goal https://github.com/TheAssassin/kodi-invidious-plugin

Maybe you both can connect and develop 1 addon with all the features instead of two? ;)

**Comment by lekma** [comment]
I'd be delighted to cooperate with anybody, but I don't see this as an issue. choice is good, isn't it? or did I miss your point?

**Comment by lekma** [comment]
Closing as invalid, because I really don't think there is an issue here :smiley: . Please, feel free to reopen if you think I missed/misunderstood your point.

**Comment by Perflyst** [comment]
I understand your point, sorry forgot to reply. Choice is good yes, but not if one has a feature that the other does not have and vice versa. We will see ;)
