### ISSUE TITLE
updating translations

### ISSUE THREAD

**Issue by lekma** [lekma/plugin.video.invidious#26]
@DavidHenryThoreau, @greenfoo: I'd like to make a new minor release with a couple of new features (feed/search history). There are a few new/modified strings needing translation. Would you guys be so kind as to update your respective contributions?

thanks in advance for your support

**Comment by greenfoo** [comment]
Done, see #27

**Comment by DavidHenryThoreau** [comment]
French translation updated : https://github.com/lekma/plugin.video.invidious/pull/28

**Comment by lekma** [comment]
thanks guys for the contributions
