### ISSUE TITLE
Disable search history

### ISSUE THREAD

**Issue by DavidHenryThoreau** [lekma/plugin.video.invidious#29]
It would be nice to disable search history on settings.

**Comment by lekma** [comment]
can you elaborate on that? is it a privacy concern? is it the additionnal ('new search' folder) step to the process of searching that is a problem?

**Comment by DavidHenryThoreau** [comment]
I'm not using the search history, yes for privacy.
Yes the additionnal folder, i mean the same behavior than in YouTube extension you can disable search history i don't want to see or other latest search and remove history after search is a bit boring.

**Comment by lekma** [comment]
would it be necessary/useful if the search history was cleared automatically when it is disabled?

**Comment by lekma** [comment]
should be implemented in d674c739e40ab356a20106ed92eff0e1929b57b6 can you test, please?

**Comment by DavidHenryThoreau** [comment]
Thanks for implementation, works well for me.
I also love the possibility to disable, popular.. :) 
Now it's a minimalist interface !

**Comment by lekma** [comment]
> Thanks for implementation, works well for me.

np. thx for testing.
