### ISSUE TITLE
Search windows pop

### ISSUE THREAD

**Issue by DavidHenryThoreau** [lekma/plugin.video.invidious#3]
When i'm stopping playing video I get search windows pop up.
It make me think about this issue :
https://github.com/jdf76/plugin.video.youtube/issues/712

**Comment by lekma** [comment]
It seems I need more time to have a look at that one (no quick fix).
If you have some knowledge on Kodi's navigation that you'd like to share...(it's strange in so many ways).

**Comment by lekma** [comment]
should be fixed in ccf1b8232d4a0922a4beb7a5cb02984f5637074c
