### ISSUE TITLE
updating translations

### ISSUE THREAD

**Issue by lekma** [lekma/plugin.video.invidious#32]
@greenfoo, @Dreamdance61: would you guys be so kind as to update your respective translations? I'd love to release a fully translated 0.2.5 and there are 2 or 3 (I think) new strings to deal with.

Also, if you feel they deserve a translation, the description/summary tags in addon.xml could use your help :smiley:

thanks in advance for your help

**Comment by Dreamdance61** [comment]
translation done, see pull request #36

**Comment by lekma** [comment]
thank you guys for the support
