### ISSUE TITLE
Invidio.us shuts down on October 1st

### ISSUE THREAD

**Issue by pitsi** [lekma/plugin.video.invidious#39]
I was reading reddit earlier and I came accross this, so I thought I should mention it here since the addon will probably stop working after that date

https://omar.yt/posts/stepping-away-from-open-source

---edit
It seems that the site will be shut down on September 1st. The api will be shut down on October 1st, so I changed the title.

**Comment by pitsi** [comment]
On top of the above, I have learned that yewtu.be has restricted access to its api and that invidious.13ad.de (reliable instance, not used by your addon atm) has moved to another server

Credit
https://github.com/trizen/straw-viewer/issues/23#issuecomment-691451171

**Comment by pitsi** [comment]
I know that, but it will be better if that (and any working) instance is already available among the ~10 ones from the public instances menu.

**Comment by lekma** [comment]
are you aware of an alternative to https://instances.invidio.us/instances.json that would be available and maintained after the 1st of october?

If so, I'd be happy to implement it in this addon.

**Comment by pitsi** [comment]
To be honest, no. But I will let you know if I find one.

**Comment by pitsi** [comment]
Just a heads up.
It's October 2nd today and the instances url is still up!

**Comment by pitsi** [comment]
Now that invidio.us is gone, can you please remove it from being the default option under general > instance name/ip address on the next update?
I installed the addon on a friend's kodi yesterday and every search returned no results because of this.
