### ISSUE TITLE
Add a licence

### ISSUE THREAD

**Issue by lienjul** [lekma/plugin.video.invidious#4]
This repository have no LICENCE file
Add a Open Source / Free Software licence.

**Comment by lekma** [comment]
Is it really needed?
Do you have suggestions for a licence type?

**Comment by lienjul** [comment]
In my mind it's better because we don't know what's the usage of your software we can.
I suggest [GPLv3](https://en.wikipedia.org/wiki/Gplv3#Version_3) which is a Free Software Licence
I can add it if you want (by creating a LICENCE in the root with GPL) ?

**Comment by lekma** [comment]
fixed in 3a26e1e2d030d248fc66ff1fad0f42ed66e333b8
