### ISSUE TITLE
Feature Request - Setting to load from youtube.com instead a invidious instance

### ISSUE THREAD

**Issue by trymeouteh** [lekma/plugin.video.invidious#43]
Please add a setting to load any video, youtube playlist, channel page from youtube.com instead from the invidious instance site without the need for the YouTube addon

**Comment by lekma** [comment]
So, there is a partial implementation of that in the latest release (no need for an additional addon anymore). But, before I go and make a setting that would change the default play method, I'd love to have some feedback on the new youtube loading. If there aren't too many complaints about unplayable videos, I'll implement the setting. In the meantime if you encounter unplayable videos when using "Play from YouTube", please, report the video id here and I'll try to find out what's wrong.

thx for your help

**Comment by probonopd** [comment]
Getting "HTTP returned code 500" when trying to use this.

**Comment by lekma** [comment]
try the other video addon in my repo
