### ISSUE TITLE
Option to change video quality

### ISSUE THREAD

**Issue by DavidHenryThoreau** [lekma/plugin.video.invidious#44]
Add an option to change the video quality

**Comment by lekma** [comment]
this could be possible for the live events (I think) but I don't see how we could do it for the mpd playlists we get from the api. if you have an idea or a suggestion for an implementation I'd be happy to have a look.

thx for your help

**Comment by DavidHenryThoreau** [comment]
To test it i'm changing quality by using front end interface for this video :
https://invidious.zapashcanon.fr/watch?v=m0Wb4HXa-sk

It seems to change quality by with : itag=NUMBER on URL

Example :

720p
https://invidious.zapashcanon.fr/latest_version?id=m0Wb4HXa-sk&itag=22

Medium quality 
https://invidious.zapashcanon.fr/latest_version?id=m0Wb4HXa-sk&itag=18

**Comment by memartinb** [comment]
+1

**Comment by lekma** [comment]
you guys know you can set a max resolution in inputstream.adaptive settings?
or even select `Manual video` (leia) or `Manually select video stream` (matrix) for the Stream selection option and then choose your quality when the video plays?
isn't that enough for your needs?
what is the specific use case?

**Comment by probonopd** [comment]
How can I tell Invidious to play all videos n 720p and without adaptive?

**Comment by DavidHenryThoreau** [comment]
inputstream.adaptive addon is intersting to set resolution but how can I set max fps ? (I'm using old cpu hardware but some videos are only available in 60fps and I'd like to set max fps to 30)

**Comment by lekma** [comment]
maybe submit a feature request to inputstream.adaptive?

**Comment by lekma** [comment]
or maybe I can filter out the 60 fps streams (I'll have a look)

**Comment by DavidHenryThoreau** [comment]
> maybe submit a feature request to inputstream.adaptive?
https://github.com/xbmc/inputstream.adaptive/issues/1359

**Comment by DavidHenryThoreau** [comment]
Answer does not fix the 60fps but only set max resolution and bandwidth bitrate.

**Comment by DavidHenryThoreau** [comment]
Another solution is to downgrade to 720p but it's quick and dirty fix.

**Comment by lekma** [comment]
this is partially implemented if you play from youtube, go to service.yt-dlp settings
