### ISSUE TITLE
Easier access to the addon's settings

### ISSUE THREAD

**Issue by pitsi** [lekma/plugin.video.invidious#45]
Can you please add an extra entry in the main menu, under search, that leads to the settings of the addon?

The main reason behind this is simple: it makes it easier switch between the instances. The way it is now, I have to exit invidious, right click on it in the list of the video addons and select settings (or press i to get to the addon's info page, then settings).

The addon has not returned a single search result for me in the last 3+ days, regardless of what instance I select in there, so I assume it is an api issue and the addon is not to blame. I have the same behavior on straw-viewer as well.

**Comment by lekma** [comment]
> Can you please add an extra entry in the main menu, under search, that leads to the settings of the addon?

> The main reason behind this is simple: it makes it easier switch between the instances. The way it is now, I have to exit invidious, right click on it in the list of the video addons and select settings (or press i to get to the addon's info page, then settings).

https://kodi.wiki/view/Basic_controls#Sideblade_Menu

![Screenshot from 2020-11-26 13-48-57](https://user-images.githubusercontent.com/1482125/100353673-2e92e480-2fef-11eb-929c-35248464d9a3.png)


> The addon has not returned a single search result for me in the last 3+ days, regardless of what instance I select in there, so I assume it is an api issue and the addon is not to blame. I have the same behavior on straw-viewer as well.

https://github.com/iv-org/invidious/issues/1488

**Comment by pitsi** [comment]
I did not notice that because I am not using the default (ugly) skin. And since the one do I use (quartz) does not provide such an option (image below, menu comes up when I press left arrow), I am out of luck.

![screenshot000](https://user-images.githubusercontent.com/5880037/100355392-589dd400-2ffa-11eb-9a5a-16bc7c9d8324.png)

As for the search issues, although mine started way before yesterday, thank you for pointing that this is a generic issue of the invidious api.

**Comment by lekma** [comment]
> I did not notice that because I am not using the default (ugly) skin. And since the one do I use (quartz) does not provide such an option (image below, menu comes up when I press left arrow), I am out of luck.

all right I'll have a look at that, but don't hold your breath, I'm quite busy with rl work atm.

**Comment by lekma** [comment]
Should be implemented in c1d5a90d2d03b95c917ae5bde65b6e85594d1d99, mind testing?

It'll be included in 0.2.7 (whenever that is out).

**Comment by pitsi** [comment]
Sure. How can I test it? I thought of git clone blablabla, but libreelec comes without git installed.

**Comment by lekma** [comment]
This should work (?):

[plugin.video.invidious-0.2.6-c1d5a90.zip](https://github.com/lekma/plugin.video.invidious/files/5611959/plugin.video.invidious-0.2.6-c1d5a90.zip)

**Comment by pitsi** [comment]
Looks great! Thank you very much :)

![screenshot000](https://user-images.githubusercontent.com/5880037/100540731-c428b100-3247-11eb-8bba-182a6a65b1b8.png)

![screenshot001](https://user-images.githubusercontent.com/5880037/100540732-c4c14780-3247-11eb-9e71-a658f1b94e05.png)
