### ISSUE TITLE
Please make it possible to order search by date (newest)

### ISSUE THREAD

**Issue by probonopd** [lekma/plugin.video.invidious#48]
Please make it possible to order search by date (newest) in addition to whatever it is ordered by default (relevance?). This should be a per-search setting, because I would like to have searches saved for some topics by date, and for other topics ordered by something else.

**Comment by lekma** [comment]
I made a tentative implementation in 0.5.3. Would you mind testing?

thx for your help

**Comment by probonopd** [comment]
Excellent @lekma it works for me. Thank you very much!
