### ISSUE TITLE
Please allow saved searches to be added to the Feed

### ISSUE THREAD

**Issue by probonopd** [lekma/plugin.video.invidious#49]
Please make it possible to view all search results in one common playlist.

Use case:
I would like to see the new videos of all my saved searches, without having to open each saved search individually to see whether there is a new video.

Rather than subscribing to channels, I would like to subscribe to topics (= saved searches).

They should be in descending release date order (=newest first).

**Comment by lekma** [comment]
I don't see how that would be possible...

**Comment by probonopd** [comment]
Do all the saved searches, then combine the results in one view?

**Comment by probonopd** [comment]
Thanks @lekma, I will test when I get https://github.com/lekma/script.module.iapc/issues/1 to work.

**Comment by probonopd** [comment]
I think this can be rephrased as:
"Allow searches, not just channels, to be added to the Feed".

**Comment by lekma** [comment]
this could be possible, is it still necessary?
