### ISSUE TITLE
Get YouTube subscrptions into this plugin's feed

### ISSUE THREAD

**Issue by probonopd** [lekma/plugin.video.invidious#53]
I like the fact that you can set up a feed here without logging into any web service. This is better for privacy.

Is there an easy way to get existing YouTube subscrptions into this plugin's feed, similar to what NewPipe is doing?

https://newpipe.net/FAQ/tutorials/import-export-data/#import-youtube

**Comment by probonopd** [comment]
Possibly using something roughly along the lines of https://github.com/gavinlyonsrepo/opml_convert_RSS (Python)?

**Comment by lekma** [comment]
outdated
