### ISSUE TITLE
PSA: New Invidious Domain (Old One Is Deprecated)

### ISSUE THREAD

**Issue by Mennaruuk** [lekma/plugin.video.invidious#54]
**Invidious official domain has moved**. I strongly suggest changing the URL for the official Invidious instance from https://invidio.us to https://invidious.io because https://invidio.us is now deprecated as per the [project's recent announcement.](https://github.com/iv-org/invidious/issues/1694)

"invidio.us is now deprecated, invidious.io is the new domain.

The invidious-redirect website ( invidio.us ) is now https://redirect.invidious.io/

The instance API ( instances.invidio.us ) is now https://api.invidious.io/

The uptimerobot page ( uptime.invidio.us ) is now https://uptime.invidious.io/

https://git.invidious.io/ redirects to the Github page of the project: https://github.com/iv-org/invidious/

https://docs.invidious.io/ redirects to the documentation website of the project: https://github.com/iv-org/documentation/

https://invidious.io/ will become in the future a "project presentation" page (like https://searx.me/ ), we will use a markdown framework like Hugo."

**Comment by lekma** [comment]
I'll make changes when they're finished setting up

thanks for the reminder

**Comment by lekma** [comment]
it seems to me there isn't any instance planned on invidious.io.

@TheFrenchGhosty: what are your plans for a default instance?

should we just remove the default and force users to choose an instance at install time?

any other ideas?

**Comment by lekma** [comment]
> @lekma redirect.invidious.io
@TheFrenchGhosty: that is not an instance, is it? does that mean no default instance (the way https://invidio.us/ was)?

**Comment by TheFrenchGhosty** [comment]
@lekma We can't afford a public instance.

We just redirect everyone to a random instance in redirect.invidious.io

**Comment by lekma** [comment]
@TheFrenchGhosty thanks for the clarification

**Comment by lekma** [comment]
@TheFrenchGhosty: last question on the subject, do you plan to ever have a public api only instance?

**Comment by TheFrenchGhosty** [comment]
@lekma Not planned, so I'm guessing no.

**Comment by lekma** [comment]
@TheFrenchGhosty: thaks again

**Comment by lekma** [comment]
90cb9f248e248ea3e4fc47dd5c6c9c40c176a017 seem to be the only change required
