### ISSUE TITLE
Compatibility with python3 and kodi 19

### ISSUE THREAD

**Issue by pitsi** [lekma/plugin.video.invidious#57]
Kodi 19 was released yesterday and it demands all addons to be made with python3 (kodi 18 supported both python3 and python2).
So, I upgraded to 19 a few minutes ago and now I am checking which of my addons are broken because of this. Invidious is one of them, so here is the issue report, plain and simple. 
There is no log to show and the addon is not even listed as available from your repo because of the above.

**Comment by pitsi** [comment]
I tried one of the forks that is already patched for python3, the one that is made by cmF3 here (and the relevant scipt.module.iapc from there)
https://github.com/cmF3/plugin.video.invidious
https://github.com/cmF3/script.module.iapc

It installs and launches as it should. As for the working part, because of the well known pita of "find an instance that works despite what their health status is", I tested ~10 of them and I was able to only find ONE that worked and returned results and that one only played videos in 144p! I will do more testing once the situation improves.

Last but not least, I know how to check if the instance is working, with the url you mentioned in #46 but I am too busy to check all of them one by one :(

**Comment by lekma** [comment]
I'm kinda working on the python3/matrix "port" (time is a limited resource...).
script.module.iapc is already "[done](https://github.com/lekma/script.module.iapc/tree/master)" (I hope).
plugin.video.invidious is next (there might problems with the repo, I don't know yet)

**Comment by lekma** [comment]
matrix version starts at 1.0.0

**Comment by pitsi** [comment]
Thank youuu! Just in time for my planned fresh install for 19!
