### ISSUE TITLE
Updating to latest version using your repository

### ISSUE THREAD

**Issue by vanfanel** [lekma/plugin.video.invidious#60]
HI there @lekma 

Thanks A LOT for this plugin, this is has been really fantastic for me in the last months :)

However, I seem to be stuck on version 0.5.7. Of course I could install current release (v1.0.0) manually, but I would like to report that, even if I have forced an update on the repository (which is now at 3.0.0), the 1.0.0 version of the plugin doesn't yet show on the plugin update menu on Kodi.

Any idea on what could be going on? Maybe v1.0.0 hastn't been pushed to the repository yet?

Thanks!

**Comment by lekma** [comment]
1.0.0 is only for matrix (v19).
are you still on leia (v18)?

**Comment by vanfanel** [comment]
@lekma Yes, still on Leia... So that was it! Understood.
I didn't know plugins were bound to Kodi versions!

**Comment by lekma** [comment]
i'll try to backport the changes from 1.0.0 in the coming days.

**Comment by vanfanel** [comment]
That would be great, yes :)
This plugin really saved YT access for me, since it's the best way to access it on a RaspberryPi-based mediacenter, and there's no stable Matrix (v19) for it yet.

**Comment by spiderbit** [comment]
Hello I have the same problem have a S905 Soc and can't update it to libreelec 19.2 so I am stuck at leia.

**Comment by lekma** [comment]
leia/0.6.1 should be on the repo, please try and report

**Comment by spiderbit** [comment]
does not work, I mean I can install the update but no search or subscription works.

**Comment by spiderbit** [comment]
Ok take it back after loading standard settings (deactivated ssl before I think) it works now... so good work.
