### ISSUE TITLE
Play on YouTube instead of Invidious

### ISSUE THREAD

**Issue by DavidHenryThoreau** [lekma/plugin.video.invidious#64]
Add option to play on YouTube instead of playing with invidious server (right click play on youtube directly by clicking ok)

**Comment by lekma** [comment]
well you have 3 options to play:
1. from invidious (default)
2. from youtube (context menu)
3. with youtube addon (context menu)

go to Settings -> Interface -> context menus for options 2 and 3
(also you need to install the official YouTube addon and set it up to use MPEG-DASH for all videos if you want to use option 3)
