### ISSUE TITLE
Right click add channel to favorites

### ISSUE THREAD

**Issue by DavidHenryThoreau** [lekma/plugin.video.invidious#7]
It would be nice to add right click in order to add channel to favorites.

**Comment by lekma** [comment]
you already can, can't you?
I'm quite sure you can do that on a channel item.
do you mean on a video item?

**Comment by DavidHenryThoreau** [comment]
Yes, i can do that on channel item.
I mean on a video item (in order not to search item on video and searching again the same on channel)

**Comment by lekma** [comment]
oh right, I'll have a look...

**Comment by lekma** [comment]
this should be working with current master.
please tell me if it is correct

**Comment by DavidHenryThoreau** [comment]
It's working, thanks.

**Comment by lekma** [comment]
implemented in 4a10bd58822ed447260b5875cc174b6170d3473b
