### ISSUE TITLE
Error Message: "Missing hash key gridChannelRenderer"

### ISSUE THREAD

**Issue by bjoern-vh** [lekma/plugin.video.invidious#70]
For some time now, every time I call the feed, I get the above error message in the right upper corner. It still works, but it takes a long time until something happens. 
I am using Kodi 19.3 on a Raspberry Pi with LibreELEC 10.0.1 and  addon in version 1.0.8.

**Comment by SethFalco** [comment]
If you're still getting this error, could you please include logs?
I assume this was an intermittent issue, or specific to the state of one of the channels in your feed was in at the time.

If you're no longer able to reproduce this, then it could be worth closing this until it's reproducible again. :thinking:

**Comment by bjoern-vh** [comment]
I did not know that the topic is still open. The error has long since resolved itself at some point and can therefore be closed :-)
