### ISSUE TITLE
Feature request: SponsorBlock

### ISSUE THREAD

**Issue by 3uryd1ce** [lekma/plugin.video.invidious#71]
This may be asking a lot. I was wondering if support for [SponsorBlock](https://sponsor.ajay.app/) is a feasible thing to include, either in this repository or as a separate companion add-on. I use the [mpv_sponsorblock_minimal](https://codeberg.org/jouni/mpv_sponsorblock_minimal) script with mpv and always miss this feature when using Invidious on Kodi. Especially on videos with a lower signal-to-noise ratio (videos with many sponsorships and unneeded fluff).

There is a [SponsorBlock add-on for YouTube](https://github.com/siku2/script.service.sponsorblock), but I would rather not use the YouTube add-on for the sake of privacy (it requires unique API keys associated to a particular identity).

Maybe it would be better to write a more generic add-on that can perform this functionality with any media file/stream, but sadly I currently lack the know-how to do it myself...

**Comment by probonopd** [comment]
I think the unique keys are needed for SponsorBlock to distinguish different clients.

Would it be possible to utilize the existing https://github.com/siku2/script.service.sponsorblock with plugin.video.invidious?
Would the modifications need to be made in script.service.sponsorblock and/or in plugin.video.invidious?

**Comment by SethFalco** [comment]
Thanks for sharing that, @probonopd.

Not merged yet, but I opened a PR there to support this addon.
I have my branch running my RockPro64, and it's working quite well, so it should be stable. :+1:

**Comment by SethFalco** [comment]
The PR above was merged!

Could be worth documenting that one can install and use that repo from the README here. I'll submit a PR later that closes this one.

**Comment by lekma** [comment]
@SethFalco: if you submit a PR, please, do it against the [sponsorblock](https://github.com/lekma/plugin.video.invidious/tree/sponsorblock) branch, thanks

**Comment by SethFalco** [comment]
Hmm, this didn't get closed. Maybe because the PR was to sponsorblock branch rather than master.
Just noting it here so when/if it does get merged to master, you know you can close this. :+1:

**Comment by lekma** [comment]
this has been implemented (though completely differently) in the latest version

**Comment by SethFalco** [comment]
> this has been implemented (though completely differently) in the latest version

Interesting! Do you know if we'd need to remove any logic from [script.service.sponsorblock](https://github.com/siku2/script.service.sponsorblock) then?

I made two PRs there which added this support externally:

* https://github.com/siku2/script.service.sponsorblock/pull/45
* https://github.com/siku2/script.service.sponsorblock/pull/49

Since your latest release, I haven't been able to get Invidious working on Kodi yet. (Not your fault!)

**Comment by lekma** [comment]
> Interesting! Do you know if we'd need to remove any logic from [script.service.sponsorblock](https://github.com/siku2/script.service.sponsorblock) then?

yeah it is not used at all, i implemented a new service [service.sponsorblock](https://github.com/lekma/service.sponsorblock) (available in my repo) and the old ways aren't used anymore.
the support for sponsorblock is limited though (meaning you get the skips and that's it for now, no voting nor reporting, and I don't think I'll do these (unless someone else contributes them))
