### ISSUE TITLE
Only Audio playing - missing video

### ISSUE THREAD

**Issue by bjoern-vh** [lekma/plugin.video.invidious#76]
Hello,

thank you very much for your addon. I love it.

When playing videos I sometimes have the problem that only the sound is played but not the picture. For some channels the error rate is very high. It doesn't matter if the addon is used in version 1.0.10 or 1.0.13 or which OS is used (tried Android and Linux). Also the Kodi version does not matter (19.3, 19.4 and 19.5 tried). Likewise, the public server instance is irrelevant. Also reinstalling the addon or even Kodi doesn't do anything. In the browser via the various Invidious instances, all videos are played without any problems.

Example:
Channel "Visualpolitik DE"

Of the most recent three videos (as of 01/01/2023 08:00 CET), two do not work.

Problems:
https://invidious.snopyta.org/watch?v=cFIuiTECevA
https://invidious.snopyta.org/watch?v=UvvY9ZeU0So

No problems:
https://invidious.snopyta.org/watch?v=xlSvbdt96jI

As I said, only in the addon, no problem in the browser.

Can you reproduce the problem and maybe even solve it?

Do others also have this problem?

Thanks a lot in advance!

Kind regards
Björn

**Comment by lekma** [comment]
I cannot reproduce your problem. I can play all 3 videos without any problem.
I would suggest you have a look at the video settings and try to select a different video stream (for that to work you need to set InputStream Adaptive -> Stream Selection -> Manually select video stream).

You could also try with the alternative play methods (context menu: Play from YouTube or Play with YouTube addon, though if you choose Play with YouTube addon you need to install the official YouTube addon and set it up to use MPEG-DASH for all videos).

hope it helps and a happy new year :)
malek

**Comment by bjoern-vh** [comment]
Thanks for your reply.

Yes, play from Youtube via context menu is working but I don't want go use Youtube, thst's whx I am here ;-)

I didn't know the settings for Inputstream Adaptive. That works for me.

Happy new year :-)

**Comment by lekma** [comment]
> I didn't know the settings for Inputstream Adaptive. That works for me.
do you mean you can select a playable video stream and the issue can be closed?

**Comment by bjoern-vh** [comment]
Yes, since I switched to manually select video stream. It works with nk problems and with every stream.

The issue can be closed.

**Comment by lekma** [comment]
great :)
