### ISSUE TITLE
Namespace clash "plugin.video.invidious"

### ISSUE THREAD

**Issue by probonopd** [lekma/plugin.video.invidious#81]
There is a namespace clash "plugin.video.invidious" with https://github.com/TheAssassin/kodi-invidious-plugin/, both use `addon id="plugin.video.invidious"`. This results in the two plugins not being able to be installed alongside each other. Also trying to update lekma/plugin.video.invidious leads to TheAssassin/kodi-invidious-plugin being installed on my system.

Cross-reference:
* https://github.com/TheAssassin/kodi-invidious-plugin/issues/26

**Comment by SethFalco** [comment]
Looks like this might no longer be relevant.
The referenced plugin just archived their public GitHub repository.

**Comment by probonopd** [comment]
I see. Thanks for checking!
