### ISSUE TITLE
Incompatible with Kodi 20 (Nexus)?

### ISSUE THREAD

**Issue by probonopd** [lekma/plugin.video.invidious#82]
When I try to install `plugin.video.invidious-1.0.27.zip` on Kodi 20.0a3-Nexus, then Kodi immediately uninstalls it, claiming it to be incompatible with the system. I am running a LibreELEC nightly build with Python 3.9.14.

**Comment by probonopd** [comment]
By pure chance digging around I found https://github.com/lekma/repository.lekma/tree/master/nexus.

It would be good if the nexus builds would also be uploaded to https://github.com/lekma/plugin.video.invidious/releases, and/or the situation be documented in https://github.com/lekma/plugin.video.invidious/blob/master/README.md.

**Comment by lekma** [comment]
you should try to install from the [repo](https://github.com/lekma/repository.lekma/releases/tag/4.0.1)

**Comment by lekma** [comment]
did you solve it?

**Comment by probonopd** [comment]
No, because i fail installing the repo. Unpacking its zip did not add the repo to Kodi. Would be nice to have instructions on how to install the repo (over ssh, as adding repos via the Kodi GUI without a proper keyboard is more than cumbersome).

**Comment by lekma** [comment]
just putting an addon in .kodi/addons won't enable it.
vnc over ssh?

**Comment by probonopd** [comment]
Thank you very much, got it to work:

```
cd ~/.kodi/addons/
rm -rf repository.lekma*
wget "https://github.com/lekma/repository.lekma/releases/download/4.0.1/repository.lekma-4.0.1.zip"
unzip repository.lekma-4.0.1.zip 
killall kodi.bin
```

Then enabled the repository in the KODI GUI, and installed Invidious from there.

It is working now :+1:
