### ISSUE TITLE
feat: display selectInstance menu post-installation

### ISSUE THREAD

**Issue by SethFalco** [lekma/plugin.video.invidious#89]
While working on #42, I noticed something that was worth resolving.

The addon defines a default instance in its settings, `invidious.snopyta.org`. However, there will eventually come a time that someone installs this extension, and their first experience with it is that everything is broken because the instance is down.

Ideally, they'll understand why and know to go to the settings, but we probably shouldn't assume that. It'd be nice to be as friendly as possible to the uninitiated.

The previous Invidious addon I used by [TheAssassin](https://github.com/TheAssassin/kodi-invidious-plugin) had this problem before in https://github.com/TheAssassin/kodi-invidious-plugin/commit/5474b454d20f16e924a936a49e1c7735f5d9bacb.

Some addons like JellyCon display a setup process once installed, for example:

![image](https://github.com/lekma/plugin.video.invidious/assets/22801583/6cf40db2-6478-46b7-b10d-69863e31513f)
> Displayed immediately after installation, showing local servers it can find.

I think this extension should do something similar, where after installation, you display the `selectInstance` menu? You can still keep the default as `invidious.snopyta.org` in case they close the menu without selecting anything.

The objective being to preserve the initial user-experience when or if `invidious.snopyta.org` is down, and the default in `settings.xml` hasn't been updated yet.

**Comment by lekma** [comment]
not a bad idea...let me think about it

**Comment by lekma** [comment]
a version of this is implementd in v3.2.6
