### ISSUE TITLE
What URL to use to install repository

### ISSUE THREAD

**Issue by furrnace** [lekma/plugin.video.invidious#97]
I would like to put an URL in `userdata/mediasources.xml` to be able to browse to the repo zip in Addons > "Install from zip file" to install the latest repo.

`https://github.com/lekma/repository.lekma/releases/` does not work for this. What should be used instead?

**Comment by lekma** [comment]
I have no idea never tried that... maybe you can try :

- https://raw.githubusercontent.com/lekma/repository.lekma/master/addons/repository.lekma/repository.lekma-4.0.1.zip
- https://github.com/lekma/repository.lekma/blob/master/addons/repository.lekma/repository.lekma-4.0.1.zip

If you download the zip file and install from a local location you can then browse the repository in kodi's interface... hope it helps.
